/**
 * Constants used throughout the application
 */
import Link from "next/link";
// Book-related constants from metadata
export const LANGUAGES = ["sanskrit", "english", "hindi", "kannada", "marathi"];
export const SCRIPTS = ["devanagari", "roman", "brahmi"];
export const CATEGORIES = ["Philosophy", "Bhashya", "Upanishad", "Tantra", "Purana", "Veda", "Yoga", "Other"];

// Pagination
export const ITEMS_PER_PAGE = 12;

// Book metadata statistics
export const BOOK_METADATA = {
  total_books: 58,
  languages: ["sanskrit", "english", "hindi", "kannada", "marathi"],
  scripts: ["devanagari", "roman", "brahmi"],
  categories: ["Philosophy", "Bhashya", "Upanishad", "Tantra", "Purana", "Veda", "Yoga", "Other"],
  year_range: {
    earliest: 1872,
    latest: 2024
  }
};

// Sort options
export const SORT_OPTIONS = [
  { value: "title-asc", label: "Title (A-Z)" },
  { value: "title-desc", label: "Title (Z-A)" },
  { value: "author-asc", label: "Author (A-Z)" },
  { value: "author-desc", label: "Author (Z-A)" },
  { value: "year-asc", label: "Year (Oldest first)" },
  { value: "year-desc", label: "Year (Newest first)" },
];

// View options
export const VIEW_OPTIONS = {
  GRID: "grid",
  LIST: "list",
};

// All books from books_metadata
export const SAMPLE_BOOKS = [
  {
    id: 1,
    title: "10 Judgements That Changed India",
    author: "Zia Mody",
    year: 2005,
    language: "sanskrit",
    script: "devanagari",
    category: "Philosophy",
    description: "A detailed analysis of ten landmark judgments that had a profound impact on India's legal and societal landscape.",
    isbn: "9780143423294",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-09-01T10:30:00.000Z",
    filePath: "/books/10 Judgements That Changed India_Zia Mody_2005_sanskrit_devanagari.pdf",
    externalLink: "https://1drv.ms/b/c/0bb4580516780fb4/EZM-BeCyXZ9JpMgbhYWr4SwBSdd4on01zYUgVW__1SibuA?e=ruOW4f"
  },
  {
    id: 2,
    title: "A Search In Secret India",
    author: "Dr Paul Brunton",
    year: 1934,
    language: "english",
    script: "roman",
    category: "Philosophy",
    description: "A fascinating journey through India in search of spiritual wisdom and mystical experiences.",
    isbn: "9780877286165",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-09-02T14:15:00.000Z",
    filePath: "/books/A Search In Secret India_Dr Paul Brunton_1934_english_roman.pdf",
    externalLink: "https://1drv.ms/b/c/0bb4580516780fb4/EQAHW3R79AxBkZmmFw-W8DwB220PiqKNZZG-lqr5y2gS9A?e=uCUClL"
  },
  {
    id: 3,
    title: "Adi Shankaracharya",
    author: "Rajiv Parihar",
    year: 2007,
    language: "english",
    script: "roman",
    category: "Philosophy",
    description: "A biography of the renowned Indian philosopher who consolidated the doctrine of Advaita Vedanta.",
    isbn: "9788172344535",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-09-03T09:45:00.000Z",
    filePath: "/books/Adi Shankaracharya_Rajiv Parihar_2007_english_roman.pdf",
    externalLink: "https://1drv.ms/b/c/0bb4580516780fb4/EdUL0rXGezNLu4tGgZyiaiABna1iy2CLKjzaV6MNxZrBxQ?e=hgNX3R"
  },
  {
    id: 4,
    title: "Gaudpadasar Part 1",
    author: "Swami Maheshanandagiri",
    year: 1951,
    language: "hindi",
    script: "devanagari",
    category: "Bhashya",
    description: "A comprehensive commentary on Gaudapada's Karika, a key text in Advaita Vedanta philosophy.",
    isbn: "9788120800533",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-09-04T11:20:00.000Z",
    filePath: "/books/Gaudpadasar Part 1_Swami Maheshanandagiri_1951_hindi_devanagari.pdf",
    externalLink: "https://1drv.ms/b/c/0bb4580516780fb4/EcsOP-xT-ipJoPs7NbejD2gBdLZsH14sx6qgTVkMOz59GA?e=aXdRK3"
  },
  {
    id: 5,
    title: "Gaudpadasar Part 2",
    author: "Swami Maheshanandagiri",
    year: 2004,
    language: "hindi",
    script: "devanagari",
    category: "Bhashya",
    description: "Second part of the comprehensive commentary on Gaudapada's philosophical work.",
    isbn: "9788120800540",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-09-05T15:40:00.000Z",
    filePath: "/books/Gaudpadasar Part 2_Swami Maheshanandagiri_2004_hindi_devanagari.pdf",
    externalLink: "https://1drv.ms/b/c/0bb4580516780fb4/EU_MlxrFvCdBi43xiVRRDfgBPG_WbLe0EIYnkqCKEhsR4g?e=rlxnpq"
  },
  {
    id: 6,
    title: "Kenopnishbdhashyadvayam",
    author: "Swami Swayamprakashgiri",
    year: 1998,
    language: "hindi",
    script: "devanagari",
    category: "Upanishad",
    description: "A dual commentary on the Kena Upanishad, exploring its philosophical dimensions.",
    isbn: "9788120802452",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-09-06T08:30:00.000Z",
    filePath: "/books/Kenopnishbdhashyadvayam_Swami Swayamprakashgiri_1998_hindi_devanagari.pdf",
    externalLink: "https://1drv.ms/b/c/0bb4580516780fb4/EUWzZ82Vxi5Og2EHYo_ZkT4BxUplDZFrvcHkeBfuNf2XNg?e=qYvFsd"
  },
  {
    id: 7,
    title: "Lakshana Samhita",
    author: "Aagama Shastra Grantha-Derebailu Harikrishna Tantri",
    year: 2017,
    language: "kannada",
    script: "brahmi",
    category: "Tantra",
    description: "A collection of tantric practices and rituals described in the Agama tradition.",
    isbn: "9788193245156",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-09-07T13:25:00.000Z",
    filePath: "/books/Lakshana Samhita_Aagama Shastra Grantha-Derebailu Harikrishna Tantri_2017_kannada_brahmi.pdf",
    externalLink: "https://1drv.ms/b/c/0bb4580516780fb4/EaExqsHsUZxLvNjwaOL7Go8BgdFPl_i2Yj63_hyTzbF1vw?e=4jy8Jf"
  },
  {
    id: 8,
    title: "Naishkmrysidhi",
    author: "Swami Maheshanand",
    year: 1996,
    language: "hindi",
    script: "devanagari",
    category: "Philosophy",
    description: "A treatise on the path of renunciation and self-realization in Hindu philosophy.",
    isbn: "9788185843452",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-09-08T09:40:00.000Z",
    filePath: "/books/Naishkmrysidhi_Swami Maheshanand_1996_hindi_devanagari.pdf",
    externalLink: "https://1drv.ms/b/c/0bb4580516780fb4/EanrNiGEjq1Ji9ZBZdq_JzMBacD8MKgOKsfJJIrH7bNXwg?e=x4xXde"
  },
  {
    id: 9,
    title: "Sarvajnana Vachanagalu",
    author: "Channappa Uttangi",
    year: 2017,
    language: "kannada",
    script: "brahmi",
    category: "Philosophy",
    description: "A collection of philosophical sayings and wisdom in Kannada tradition.",
    isbn: "9788193567128",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-09-09T10:15:00.000Z",
    filePath: "/books/Sarvajnana Vachanagalu _Channappa Uttangi_2017_kannada_brahmi.pdf",
    externalLink: "https://1drv.ms/b/c/0bb4580516780fb4/Ea7FXS7kbz5Bq3rLv9q1_jcBbEp7-AAkHV4XZFiPUDPtnw?e=eGqipm"
  },
  {
    id: 10,
    title: "Shiva Geeta Bhashyam",
    author: "Shrimat Abhinav Narshimha Bharathi",
    year: 1962,
    language: "sanskrit",
    script: "devanagari",
    category: "Philosophy, Bhashya",
    description: "An important text explaining the philosophical teachings of Lord Shiva.",
    isbn: "9788185208985",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-09-10T14:20:00.000Z",
    filePath: "/books/Shiva Geeta Bhashyam_Shrimat Abhinav Narshimha Bharathi_1962_sanskrit_devanagari.pdf",
    externalLink: "https://1drv.ms/b/c/0bb4580516780fb4/EfA_nIG25uZAkS21Bo2fGBABVTh9P6-Bmk7BGdkRYqD2RQ?e=9HORAv"
  },
  {
    id: 11,
    title: "Shrada Chandrika",
    author: "Shri Divakara bhatta",
    year: 1934,
    language: "sanskrit",
    script: "devanagari",
    category: "Purana",
    description: "A text illuminating the concept of devotion and faith in Hindu tradition.",
    isbn: "9788175050723",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-09-11T11:30:00.000Z",
    filePath: "/books/Shrada Chandrika_Shri Divakara bhatta_1934_sanskrit_devanagari.pdf",
    externalLink: "https://1drv.ms/b/c/0bb4580516780fb4/EUtZ1v5waeNHiGJkd4Ussg0BYiA3kdh9FommPZTziCeeKw?e=DAcTJi"
  },
  {
    id: 12,
    title: "Shree Chitrapur Guru Parampara Charitrapur Saramrit",
    author: "Shri durganand shivaram maraballi",
    year: 2002,
    language: "marathi",
    script: "devanagari",
    category: "Purana",
    description: "Chronicles of the Guru lineage of Chitrapur Math tradition.",
    isbn: "9788190424219",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-09-12T09:45:00.000Z",
    filePath: "/books/Shree Chitrapur Guru Parampara Charitrapur Saramrit_Shri durganand shivaram maraballi_2002_marathi_devanagari.pdf",
    externalLink: "https://1drv.ms/b/c/0bb4580516780fb4/EWC2lHfksbdAu4lnrPIlMSUBLuw2qfoOT-5_EMRRHH8ZRg?e=uPJ47T"
  },
  {
    id: 13,
    title: "Shri Lalita Sahasranama Stotram Manava Prabodhan Nysa Bikaner",
    author: "Vasini, Kameshvari, Aruna, Vimala, Jayani, Modini, Sarveshvari, and Kaulini",
    year: 2019,
    language: "sanskrit",
    script: "devanagari",
    category: "Tantra",
    description: "A sacred text containing the thousand names of the Divine Mother Lalita with ritual practices.",
    isbn: "9788120818330",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-09-13T16:50:00.000Z",
    filePath: "/books/Shri Lalita Sahasranama Stotram Manava Prabodhan Nysa Bikaner_unknown_2019_sanskrit_devanagari.pdf",
    externalLink: "https://1drv.ms/b/c/0bb4580516780fb4/EUQPtpBQGAhPmpCwdVcbdUoBP2dBAq3Exz7wjOnfz0TR8Q?e=a81oZu"
  },
  {
    id: 14,
    title: "Shri Raman Gita",
    author: "Shri Vashistha Ganapati Muni-1",
    year: 1946,
    language: "sanskrit",
    script: "devanagari",
    category: "Philosophy",
    description: "A philosophical text in the form of dialogues with Sri Ramana Maharshi.",
    isbn: "9788182881228",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-09-14T10:05:00.000Z",
    filePath: "/books/Shri Raman Gita_Shri Vashistha Ganapati Muni-1_1946_sanskrit_devanagari.pdf",
    externalLink: "https://1drv.ms/b/c/0bb4580516780fb4/Eavh9jTxTWpLu_6b5dMDyo8Bwk-bD4ytYoyfaDPdn76Krw?e=K738wK"
  },
  {
    id: 15,
    title: "Shri-Vidya-Ratna-Sutram-of-Gaud-Datiya",
    author: "Gaudpadacharya",
    year: 2006,
    language: "sanskrit",
    script: "devanagari",
    category: "Tantra",
    description: "Precious sutras on Sri Vidya tantric practices and philosophy.",
    isbn: "9788186050217",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-09-15T12:20:00.000Z",
    filePath: "/books/Shri-Vidya-Ratna-Sutram-of-Gaud-Datiya_Gaudpadacharya_2006_sanskrit_devanagari.pdf",
    externalLink: "https://1drv.ms/b/c/0bb4580516780fb4/EQrtu3_0bjdOj5sAF2LvvHgBwdslqHr2N8czBwuZnTWKow?e=6mcm4F"
  },
  {
    id: 16,
    title: "Shrimooka panchashathi",
    author: "Lakshmi Halasyam",
    year: 2005,
    language: "sanskrit",
    script: "devanagari",
    category: "Philosophy",
    description: "A collection of five hundred verses in praise of the Divine Mother.",
    isbn: "9788185141978",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-09-16T14:30:00.000Z",
    filePath: "/books/Shrimooka panchashathi_Lakshmi Halasyam_2005_sanskrit_devanagari.pdf",
    externalLink: "https://1drv.ms/b/c/0bb4580516780fb4/ERQj8qdMZhpCrmvLvkKHpsABwIM--mBWNu1_kK4ZOWHu-w?e=eXfPGv"
  },
  {
    id: 17,
    title: "South Indian Bronzes",
    author: "C.Sivaramamurti",
    year: 1963,
    language: "english",
    script: "roman",
    category: "Purana",
    description: "A detailed study of ancient South Indian bronze sculptures and their cultural significance.",
    isbn: "9788185054186",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-09-17T09:25:00.000Z",
    filePath: "/books/South Indian Bronzes_C.Sivaramamurti_1963_english_roman.pdf",
    externalLink: "https://1drv.ms/b/c/0bb4580516780fb4/EWalDVCDDwFEvIxJBjeAva4BlC67hKwIvUb68CMMnqN80g?e=eeUghg"
  },
  {
    id: 18,
    title: "Space-Collins",
    author: "David Hawksett",
    year: 2005,
    language: "english",
    script: "roman",
    category: "Philosophy",
    description: "An exploration of philosophical concepts related to space, existence, and cosmic understanding.",
    isbn: "9780007211357",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-09-18T11:15:00.000Z",
    filePath: "/books/Space-Collins_David Hawksett_2005_english_roman.pdf",
    externalLink: "https://1drv.ms/b/c/0bb4580516780fb4/EdHJG32oXqBDnI1bp_NK0LwBkhKpp3yNk_egfCmNIHdmHQ?e=IsdCDO"
  },
  {
    id: 19,
    title: "Stutimanjari Kannada",
    author: "Malini Madiman Pachi",
    year: 2013,
    language: "kannada",
    script: "brahmi",
    category: "Veda",
    description: "A bouquet of hymns and prayers in Kannada based on Vedic traditions.",
    isbn: "9788193255629",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-09-19T13:40:00.000Z",
    filePath: "/books/Stutimanjari Kannada_Malini Madiman Pachi_2013_kannada_brahmi.pdf",
    externalLink: "https://1drv.ms/b/c/0bb4580516780fb4/EYbIqEpkdxROvodI94OQVgcB7bV1f8IszxloZTjOVCFuAw?e=AfZsJk"
  },
  {
    id: 20,
    title: "Tara-Kalpa-Taru",
    author: "Ramanand Sharma,Ruthsheel sharma",
    year: 2006,
    language: "hindi",
    script: "devanagari",
    category: "Philosophy",
    description: "A comprehensive work on the goddess Tara and her philosophical dimensions.",
    isbn: "9788186050743",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-09-20T10:10:00.000Z",
    filePath: "/books/Tara-Kalpa-Taru_Ramanand Sharma,Ruthsheel sharma_2006_hindi_devanagari.pdf",
    externalLink: "https://1drv.ms/b/c/0bb4580516780fb4/EVWnbTUfNIRLsE5CyED9HVUBBJDohE2id_rZ2fe48Uo5Rw?e=eLJiYt"
  },
  {
    id: 21,
    title: "kannada booklet",
    author: "Kuvempu, K. Shivaram Karanth, Poornachandra Tejaswi, and B. M. Srikanthaiah",
    year: 1918,
    language: "kannada",
    script: "brahmi",
    category: "Veda",
    description: "A classic collection of Vedic knowledge translated and interpreted in Kannada by renowned scholars.",
    isbn: "9788193629581",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-09-21T08:55:00.000Z",
    filePath: "/books/kannada booklet_Unknown_1918_kannada_brahmi.pdf",
    downloadLink: "/public/books/kannada booklet_Unknown_1918_kannada_brahmi.pdf",
    externalLink: "https://1drv.ms/b/c/0bb4580516780fb4/EVIx9FmXB5FCgjyAD3L5S_MBhT7D1a0A29zMQiSJ4tDA6A?e=qIaMw4"
  },
  {
    id: 22,
    title: "Autobiography of a Yogi",
    author: "Paramahansa Yogananda",
    year: 1946,
    language: "english",
    script: "roman",
    category: "Yoga",
    description: "A spiritual classic that recounts the life of Paramahansa Yogananda and his encounters with spiritual figures of both the Eastern and Western traditions.",
    isbn: "9780876120798",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-09-22T09:30:00.000Z",
    filePath: "/books/Autobiography-of-a-Yogi_Paramahansa-Yogananda_1946_english_roman.pdf",
    externalLink: "https://1drv.ms/b/c/0bb4580516780fb4/EU50IBf6_mFPo-tGzQ3WoRoBcsO_Fx02qan_dHIwxjKmiQ?e=AC6bGK"
  },
  {
    id: 23,
    title: "The Rigveda",
    author: "Ralph T.H. Griffith",
    year: 1896,
    language: "english",
    script: "roman",
    category: "Veda",
    description: "A seminal translation of the ancient Rigveda, one of the four canonical sacred texts of Hinduism known as the Vedas.",
    isbn: "9780140449891",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-09-23T11:45:00.000Z",
    filePath: "/books/The Rigvesda_Ralph-t-h-griffith_1896_english_roman.pdf",
    externalLink: "https://1drv.ms/b/c/0bb4580516780fb4/EYcBXnCIQfRNn6oTOHIqKsYBq960PpJ2sZ4nDsCt3tKivw?e=Mt63RF"
  },
  {
    id: 24,
    title: "SiddhantakaumudiVol1Part1",
    author: "Sandhi-SrRay",
    year: 1926,
    language: "english",
    script: "roman",
    category: "Bhashya",
    description: "A foundational text on Sanskrit grammar and linguistics, with detailed explanations of grammatical rules.",
    isbn: "9788120800724",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-10-01T09:00:00.000Z",
    filePath: "/books/SiddhantakaumudiVol1Part1-Sandhi-SrRay1926.pdf",
    externalLink: "https://adminct-my.sharepoint.com/:b:/r/personal/varun_mallapur_chitrapurmath_net_in/Documents/Scanned%20Books/Eng/1.SiddhantakaumudiVol1Part1-Sandhi-SrRay1926.pdf?csf=1&web=1&e=Q5LR8w"
  },
  {
    id: 25,
    title: "10 Judgements That Changed India",
    author: "Zia Mody",
    year: 2013,
    language: "english",
    script: "roman",
    category: "Philosophy",
    description: "An insightful analysis of ten landmark judgments that transformed India's legal landscape and social framework.",
    isbn: "9780143429982",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-10-01T10:15:00.000Z",
    filePath: "/books/10 Judgements That Changed India_Zia Mody.pdf",
    externalLink: "https://adminct-my.sharepoint.com/:b:/r/personal/varun_mallapur_chitrapurmath_net_in/Documents/Scanned%20Books/Eng/10%20Judgements%20That%20Changed%20India_Zia%20Mody.pdf?csf=1&web=1&e=k8RKl8"
  },
  {
    id: 26,
    title: "112 Upanishads Volume 1",
    author: "K L Joshi",
    year: 2004,
    language: "english",
    script: "roman",
    category: "Upanishad",
    description: "A comprehensive collection of Upanishadic texts with translations and interpretations, first volume.",
    isbn: "9788173052408",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-10-01T11:30:00.000Z",
    filePath: "/books/112 Upanishads Volume 1 - K L Joshi  - Parimal Publications - Delhi5-7-13.pdf",
    externalLink: "https://adminct-my.sharepoint.com/:b:/r/personal/varun_mallapur_chitrapurmath_net_in/Documents/Scanned%20Books/Eng/112%20Upanishads%20Volume%201%20-%20K%20L%20Joshi%20%20-%20Parimal%20Publications%20-%20Delhi5-7-13.pdf?csf=1&web=1&e=WcEbSH"
  },
  {
    id: 27,
    title: "112 Upanishads Volume 2",
    author: "K L Joshi",
    year: 2004,
    language: "english",
    script: "roman",
    category: "Upanishad",
    description: "The second volume of the comprehensive collection of Upanishadic texts with scholarly annotations.",
    isbn: "9788173052415",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-10-01T12:45:00.000Z",
    filePath: "/books/112 Upanishads Volume 2 - Edited by K.L.Joshi & Team.pdf",
    externalLink: "https://adminct-my.sharepoint.com/:b:/r/personal/varun_mallapur_chitrapurmath_net_in/Documents/Scanned%20Books/Eng/112%20Upanishads%20Volume%202%20-%20Edited%20by%20K.L.Joshi%20%26%20Team.pdf?csf=1&web=1&e=NcSofK"
  },
  {
    id: 28,
    title: "1872 - Yajnasudhanidhi",
    author: "Rev.F.Kittel",
    year: 1872,
    language: "english",
    script: "roman",
    category: "Tantra",
    description: "A historical text on Vedic sacrificial rituals and their significance in Hindu traditions.",
    isbn: "9780198047759",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-10-02T09:15:00.000Z",
    filePath: "/books/1872 - Yajnasudhanidhi.pdf",
    externalLink: "https://adminct-my.sharepoint.com/:b:/r/personal/varun_mallapur_chitrapurmath_net_in/Documents/Scanned%20Books/Eng/1872%20-%20Yajnasudhanidhi.pdf?csf=1&web=1&e=gMdjEq"
  },
  {
    id: 29,
    title: "300 Years of Bliss",
    author: "Souvenir",
    year: 2007,
    language: "english",
    script: "roman",
    category: "Philosophy",
    description: "A commemorative volume celebrating three centuries of spiritual wisdom and cultural heritage.",
    isbn: "9788190678032",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-10-02T10:30:00.000Z",
    filePath: "/books/300 Years of Bliss - Souvenir.pdf",
    externalLink: "https://adminct-my.sharepoint.com/:b:/r/personal/varun_mallapur_chitrapurmath_net_in/Documents/Scanned%20Books/Eng/300%20Years%20of%20Bliss%20-%20Souvenir.pdf?csf=1&web=1&e=grqBIh"
  },
  {
    id: 30,
    title: "A Manual of Hindu Ethics",
    author: "G A Chandavarkar",
    year: 2012,
    language: "english",
    script: "roman",
    category: "Philosophy",
    description: "A comprehensive guide to Hindu ethical principles and their application in modern life.",
    isbn: "9788129120403",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-10-02T14:00:00.000Z",
    filePath: "/books/A Manual of Hindu Ethics - G A Chandavarkar - Rupa and co.pdf",
    externalLink: "https://adminct-my.sharepoint.com/:b:/r/personal/varun_mallapur_chitrapurmath_net_in/Documents/Scanned%20Books/Eng/A%20Manual%20of%20Hindu%20Ethics%20-%20G%20A%20Chandavarkar%20-%20Rupa%20and%20co.pdf?csf=1&web=1&e=ygcxow"
  },
  {
    id: 31,
    title: "A Riddle Unravelled",
    author: "Dr.Gopal.S.hattiangadi",
    year: 2002,
    language: "english",
    script: "roman",
    category: "Philosophy",
    description: "An exploration of philosophical enigmas and their solutions through Hindu philosophical frameworks.",
    isbn: "9788175258518",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-10-03T09:00:00.000Z",
    filePath: "/books/A Riddle Unravelled_Dr.Gopal.S.hattiangadi_Bombay-2002.pdf",
    externalLink: "https://adminct-my.sharepoint.com/:b:/r/personal/varun_mallapur_chitrapurmath_net_in/Documents/Scanned%20Books/Eng/A%20Riddle%20Unravelled_Dr.Gopal.S.hattiangadi_Bombay-2002..pdf?csf=1&web=1&e=bRuThi"
  },
  {
    id: 32,
    title: "A Personal Religion Of Your Own",
    author: "Ramesh S.Balsekar",
    year: 2006,
    language: "english",
    script: "roman",
    category: "Philosophy",
    description: "A guide to developing a personalized spiritual path while drawing from traditional wisdom.",
    isbn: "9788188479306",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-10-03T10:30:00.000Z",
    filePath: "/books/A Personal Religion Of Your Own - Ramesh S. Balsekar.pdf",
    externalLink: "https://adminct-my.sharepoint.com/:b:/r/personal/varun_mallapur_chitrapurmath_net_in/Documents/Scanned%20Books/Eng/A%20Personal%20Religion%20Of%20Your%20Own%20-%20Ramesh%20S.%20Balsekar.pdf?csf=1&web=1&e=YJDIDj"
  },
  {
    id: 33,
    title: "A Sanskrit English Dictionary",
    author: "M.Monier Williams",
    year: 2008,
    language: "english",
    script: "roman",
    category: "Bhashya",
    description: "A comprehensive Sanskrit-English dictionary with etymological and philological references.",
    isbn: "9788120800656",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-10-03T14:15:00.000Z",
    filePath: "/books/A Sanskrit English Dictionary V - M. Monier - Williams.pdf",
    externalLink: "https://adminct-my.sharepoint.com/:b:/r/personal/varun_mallapur_chitrapurmath_net_in/Documents/Scanned%20Books/Eng/A%20Sanskrit%20English%20Dictionary%20V%20-%20M.%20Monier%20-%20Williams.pdf?csf=1&web=1&e=LG7KN3"
  },
  {
    id: 34,
    title: "A Sage Par Excellence",
    author: "Sri Srikantha Shastri",
    year: 1924,
    language: "english",
    script: "roman",
    category: "Philosophy",
    description: "A biographical account of a renowned spiritual master and his teachings.",
    isbn: "9788190123457",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-10-04T09:45:00.000Z",
    filePath: "/books/A Sage Par Excellence - Biograp - Unknown.pdf",
    externalLink: "https://adminct-my.sharepoint.com/:b:/r/personal/varun_mallapur_chitrapurmath_net_in/Documents/Scanned%20Books/Eng/A%20Sage%20Par%20Excellence%20-%20Biograp%20-%20Unknown.pdf?csf=1&web=1&e=09Esf6"
  },
  {
    id: 35,
    title: "A Search In Secret India",
    author: "Dr Paul Brunton",
    year: 1934,
    language: "english",
    script: "roman",
    category: "Yoga",
    description: "A fascinating travelogue of a westerner's spiritual journey through India in search of yogic wisdom.",
    isbn: "9788172240493",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-10-04T11:30:00.000Z",
    filePath: "/books/A Search In Secret India_Dr Paul Brunton_B I Publications Pvt Ltd_New Delhi.pdf",
    externalLink: "https://adminct-my.sharepoint.com/:b:/r/personal/varun_mallapur_chitrapurmath_net_in/Documents/Scanned%20Books/Eng/A%20Search%20In%20Secret%20India_Dr%20Paul%20Brunton_B%20I%20Publications%20Pvt%20Ltd_New%20Delhi.pdf?csf=1&web=1&e=VzJwMF"
  },
  {
    id: 36,
    title: "Abhinavagupta- A Trident of Wisdom Translation of Paratrisika Vivarana",
    author: "Jaideva Singh",
    year: 1988,
    language: "english",
    script: "roman",
    category: "Tantra",
    description: "A scholarly translation and interpretation of a key tantric text by the renowned philosopher Abhinavagupta.",
    isbn: "9788120809321",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-10-04T15:00:00.000Z",
    filePath: "/books/Abhinavagupta- A Trident of Wisdom Translation of Paratrisika Vivarana - Jaideva Singh.pdf",
    externalLink: "https://adminct-my.sharepoint.com/:b:/r/personal/varun_mallapur_chitrapurmath_net_in/Documents/Scanned%20Books/Eng/Abhinavagupta-%20A%20Trident%20of%20Wisdom%20Translation%20of%20Paratrisika%20Vivarana%20-%20Jaideva%20Singh.pdf?csf=1&web=1&e=KM5tva"
  },
  {
    id: 37,
    title: "Adi Shankaracharya",
    author: "Rajiv Parihar",
    year: 2007,
    language: "english",
    script: "roman",
    category: "Philosophy",
    description: "A comprehensive biography of Adi Shankaracharya, the great philosopher who consolidated the doctrine of Advaita Vedanta.",
    isbn: "9788172345662",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-10-05T08:45:00.000Z",
    filePath: "/books/Adi Shankaracharya (Eng) - Rajiv Parihar.pdf",
    externalLink: "https://adminct-my.sharepoint.com/:b:/r/personal/varun_mallapur_chitrapurmath_net_in/Documents/Scanned%20Books/Eng/Adi%20Shankaracharya%20(Eng)%20-%20Rajiv%20Parihar.pdf?csf=1&web=1&e=7l9AoU"
  },
  {
    id: 38,
    title: "Five Hundred Indian Plants",
    author: "K.R Sreenivasa Murthy",
    year: 1908,
    language: "english",
    script: "roman",
    category: "Tantra",
    description: "A botanical catalog of Indian plants with their medicinal and ritual uses in traditional tantric practices.",
    isbn: "9780198123514",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-10-05T10:00:00.000Z",
    filePath: "/books/Five Hundred Indian Plants.pdf",
    externalLink: "https://adminct-my.sharepoint.com/:b:/r/personal/varun_mallapur_chitrapurmath_net_in/Documents/Scanned%20Books/Eng/Five%20Hundred%20Indian%20Plants.pdf?csf=1&web=1&e=FSt0RJ"
  },
  {
    id: 39,
    title: "Foundations of Dharma",
    author: "Jnanasamvardhani Granthamala",
    year: 2006,
    language: "english",
    script: "roman",
    category: "Philosophy",
    description: "An exploration of the foundational principles of dharma in Hindu philosophy and practice.",
    isbn: "9788179272195",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-10-05T11:15:00.000Z",
    filePath: "/books/Foundations of Dharma-Swami Paramananda Bharati Swamiji- Jnanasamvardhani Granthamala.pdf",
    externalLink: "https://adminct-my.sharepoint.com/:b:/r/personal/varun_mallapur_chitrapurmath_net_in/Documents/Scanned%20Books/Eng/Foundations%20of%20Dharma-Swami%20Paramananda%20Bharati%20Swamiji-%20Jnanasamvardhani%20Granthamala.pdf?csf=1&web=1&e=XqGo1w"
  },
  {
    id: 40,
    title: "Gods,Sages and Kings-Vedic Secrets of Ancient Civilization",
    author: "David Frawley",
    year: 1993,
    language: "english",
    script: "roman",
    category: "Philosophy",
    description: "An exploration of Vedic civilization, its deities, sages, rulers, and hidden knowledge systems.",
    isbn: "9788120815001",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-10-05T14:30:00.000Z",
    filePath: "/books/Gods, Sages and Kings-Vedic Secrets of Ancient Civilization - David Frawley.pdf",
    externalLink: "https://adminct-my.sharepoint.com/:b:/r/personal/varun_mallapur_chitrapurmath_net_in/Documents/Scanned%20Books/Eng/Gods,%20Sages%20and%20Kings-Vedic%20Secrets%20of%20Ancient%20Civilization%20-%20David%20Frawley.pdf?csf=1&web=1&e=Z5nIA2"
  },
  {
    id: 41,
    title: "Collins gem space",
    author: "David Hawksett",
    year: 2005,
    language: "english",
    script: "roman",
    category: "Other",
    description: "A comprehensive pocket guide to astronomy and space exploration with detailed illustrations and facts.",
    isbn: "9780007197422",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-10-05T15:00:00.000Z",
    filePath: "/books/Space-Collins Gem_Cally Oldershaw_Harper Collins Publishers_U.K.pdf",
    externalLink: "https://adminct-my.sharepoint.com/:b:/r/personal/varun_mallapur_chitrapurmath_net_in/Documents/Scanned%20Books/Eng/Space-Collins%20Gem_Cally%20Oldershaw_Harper%20Collins%20Publishers_U.K...pdf?csf=1&web=1&e=vQQTgB"
  },
  {
    id: 42,
    title: "South Indian Bronzes",
    author: "C Sivaramamurti",
    year: 1981,
    language: "english",
    script: "roman",
    category: "Other",
    description: "A scholarly study of ancient South Indian bronze sculptures, their artistic significance and cultural heritage.",
    isbn: "9788170860136",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-10-05T15:15:00.000Z",
    filePath: "/books/South Indian Bronzes_C.Sivaramamurti_Lalit Kala Akademi,New Delhi.pdf",
    externalLink: "https://adminct-my.sharepoint.com/:b:/r/personal/varun_mallapur_chitrapurmath_net_in/Documents/Scanned%20Books/Eng/South%20Indian%20Bronzes_C.Sivaramamurti_Lalit%20Kala%20Akademi,New%20Delhi..pdf?csf=1&web=1&e=Efy0tU"
  },
  {
    id: 43,
    title: "My Lord,the Mystery",
    author: "Ardhanarishwara",
    year: 2010,
    language: "english",
    script: "roman",
    category: "Philosophy",
    description: "A spiritual exploration of divine mysteries through the lens of Hindu philosophy by Swami Iswarananda Giri.",
    isbn: "9788189640477",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-10-05T15:30:00.000Z",
    filePath: "/books/My Lord, The Mystery - Ardhanar - Swami Iswarananda Giri.pdf",
    externalLink: "https://adminct-my.sharepoint.com/:b:/r/personal/varun_mallapur_chitrapurmath_net_in/Documents/Scanned%20Books/Eng/My%20Lord,%20The%20Mystery%20-%20Ardhanar%20-%20Swami%20Iswarananda%20Giri.pdf?csf=1&web=1&e=IkZ4k3"
  },
  {
    id: 44,
    title: "Narendra Modi-A Political biography",
    author: "Andy Marino",
    year: 2014,
    language: "english",
    script: "roman",
    category: "Other",
    description: "A comprehensive political biography of Indian Prime Minister Narendra Modi, examining his rise in Indian politics.",
    isbn: "9789351362654",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-10-05T15:45:00.000Z",
    filePath: "/books/Narendra Modi_A Political Biography_Andy Marino_Harper Collins Publishers India_Noida.pdf",
    externalLink: "https://adminct-my.sharepoint.com/:b:/r/personal/varun_mallapur_chitrapurmath_net_in/Documents/Scanned%20Books/Eng/Narendra%20Modi_A%20Political%20Biography_Andy%20Marino_Harper%20Collins%20Publishers%20India_Noida.pdf?csf=1&web=1&e=uuXges"
  },
  {
    id: 45,
    title: "Migrations of Saraswat Brahmins in India",
    author: "D V Nadkarny",
    year: 2000,
    language: "english",
    script: "roman",
    category: "Other",
    description: "A historical study of the migration patterns of Saraswat Brahmin communities across different regions of India.",
    isbn: "9780123456789",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-10-05T16:00:00.000Z",
    filePath: "/books/Migrations of Saraswat Brahmins in India D V Nadakarni.pdf",
    externalLink: "https://adminct-my.sharepoint.com/:b:/r/personal/varun_mallapur_chitrapurmath_net_in/Documents/Scanned%20Books/Eng/Migrations%20of%20Saraswat%20Brahmins%20in%20India%20D%20V%20Nadakarni.pdf?csf=1&web=1&e=OpHEgO"
  },
  {
    id: 46,
    title: "Manual of Hindu Ethics",
    author: "G A Chandavarkar",
    year: 2010,
    language: "english",
    script: "roman",
    category: "Philosophy",
    description: "A comprehensive guide to Hindu ethical principles and their application in daily life and society.",
    isbn: "9788129116727",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-10-05T16:15:00.000Z",
    filePath: "/books/Manual of Hindu Ethics, A - G A Chandavarkar.pdf",
    externalLink: "https://adminct-my.sharepoint.com/:b:/r/personal/varun_mallapur_chitrapurmath_net_in/Documents/Scanned%20Books/Eng/Manual%20of%20Hindu%20Ethics,%20A%20-%20G%20A%20Chandavarkar.pdf?csf=1&web=1&e=A19g3U"
  },
  {
    id: 47,
    title: "Lotus Blooms",
    author: "Swami ishwarananda Giri",
    year: 2009,
    language: "english",
    script: "roman",
    category: "Philosophy",
    description: "A spiritual text exploring the unfolding of consciousness symbolized by the lotus flower in Hindu philosophy.",
    isbn: "9788189640484",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-10-05T16:30:00.000Z",
    filePath: "/books/Lotus Blooms - Swami Ishwaranand Giri.pdf",
    externalLink: "https://adminct-my.sharepoint.com/:b:/r/personal/varun_mallapur_chitrapurmath_net_in/Documents/Scanned%20Books/Eng/Lotus%20Blooms%20-%20Swami%20Ishwaranand%20Giri.pdf?csf=1&web=1&e=l3KLZE"
  },
  {
    id: 48,
    title: "Man's Search For Meaning",
    author: "Viktore Frankl",
    year: 2004,
    language: "english",
    script: "roman",
    category: "Philosophy",
    description: "A profound exploration of human purpose and meaning based on the author's experiences as a Holocaust survivor.",
    isbn: "9781844132393",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-10-05T16:45:00.000Z",
    filePath: "/books/Mans Search For Meaning_Viktor E Frankl_Rider_London.pdf",
    externalLink: "https://adminct-my.sharepoint.com/:b:/r/personal/varun_mallapur_chitrapurmath_net_in/Documents/Scanned%20Books/Eng/Mans%20Search%20For%20Meaning_Viktor%20E%20Frankl_Rider_London.pdf?csf=1&web=1&e=x9RVC4"
  },
  {
    id: 49,
    title: "Looking Back",
    author: "Dhondo Keshav Karve",
    year: 1936,
    language: "english",
    script: "roman",
    category: "Other",
    description: "The autobiography of social reformer Dhondo Keshav Karve, recounting his life and work for women's education in India.",
    isbn: "9780123456978",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-10-05T17:00:00.000Z",
    filePath: "/books/Looking Back_Dhondo Keshav Karve.pdf",
    externalLink: "https://adminct-my.sharepoint.com/:b:/r/personal/varun_mallapur_chitrapurmath_net_in/Documents/Scanned%20Books/Eng/Looking%20Back_Dhondo%20Keshav%20Karve.pdf?csf=1&web=1&e=PQ6ZR7"
  },
  {
    id: 50,
    title: "Light On The Yoga sutras of Patanjali",
    author: "B K S Iyengar",
    year: 1993,
    language: "english",
    script: "roman",
    category: "Yoga",
    description: "A definitive guide to understanding and practicing Patanjali's Yoga Sutras by renowned yoga master B.K.S. Iyengar.",
    isbn: "9780007145164",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-10-05T17:15:00.000Z",
    filePath: "/books/Light on the Yoga Sutras of Patanjali_ B.K.S.Iyengar_ Thorsons, London.pdf",
    externalLink: "https://adminct-my.sharepoint.com/:b:/r/personal/varun_mallapur_chitrapurmath_net_in/Documents/Scanned%20Books/Eng/Light%20on%20the%20Yoga%20Sutras%20of%20Patanjali_%20B.K.S.Iyengar_%20Thorsons,%20London.pdf?csf=1&web=1&e=VyCowH"
  },
  {
    id: 51,
    title: "Kailash and Manasarovar - A Quest Beyond The Himalaya",
    author: "DEB Mukharji",
    year: 2013,
    language: "english",
    script: "roman",
    category: "Philosophy",
    description: "A spiritual and geographical exploration of the sacred sites of Mount Kailash and Lake Manasarovar in Tibet.",
    isbn: "9789383098057",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-10-05T17:30:00.000Z",
    filePath: "/books/Kailash And Mansarovar-A Quest Beyond The Himalaya_Deb Mukharji_Niyogi Books_New Delhi.pdf",
    externalLink: "https://adminct-my.sharepoint.com/:b:/r/personal/varun_mallapur_chitrapurmath_net_in/Documents/Scanned%20Books/Eng/Kailash%20And%20Mansarovar-A%20Quest%20Beyond%20The%20Himalaya_Deb%20Mukharji_Niyogi%20Books_New%20Delhi..pdf?csf=1&web=1&e=2jxHoE"
  },
  {
    id: 52,
    title: "Kailas - Manasarovar",
    author: "Swami Pranavananda",
    year: 2008,
    language: "english",
    script: "roman",
    category: "Philosophy",
    description: "A detailed account of the holy Mount Kailas and Lake Manasarovar, their geography, history, and spiritual significance.",
    isbn: "9788171674121",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-10-05T17:45:00.000Z",
    filePath: "/books/Kailas - Manasarovar (Eng) - Swami Pranavanand.pdf",
    externalLink: "https://adminct-my.sharepoint.com/:b:/r/personal/varun_mallapur_chitrapurmath_net_in/Documents/Scanned%20Books/Eng/Kailas%20-%20Manasarovar%20(Eng)%20-%20Swami%20Pranavanand.pdf?csf=1&web=1&e=Mrsbrm"
  },
  {
    id: 53,
    title: "Jungian Psychology",
    author: "Anthony Stevens",
    year: 1990,
    language: "english",
    script: "roman",
    category: "Philosophy",
    description: "An accessible introduction to Carl Jung's psychological theories and their application to understanding human behavior.",
    isbn: "9780192192707",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-10-05T18:00:00.000Z",
    filePath: "/books/Jungian Psychology (Eng) - Anthony Stevens (1331).pdf",
    externalLink: "https://adminct-my.sharepoint.com/:b:/r/personal/varun_mallapur_chitrapurmath_net_in/Documents/Scanned%20Books/Eng/Jungian%20Psychology%20(Eng)%20-%20Anthony%20Stevens%20(1331).pdf?csf=1&web=1&e=ClmXaM"
  },
  {
    id: 54,
    title: "Journey To Ixtlan",
    author: "Carlos Castaneda",
    year: 1972,
    language: "english",
    script: "roman",
    category: "Philosophy",
    description: "A narrative account of Castaneda's apprenticeship with Don Juan Matus, exploring alternative ways of perceiving reality.",
    isbn: "9780671213992",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-10-05T18:15:00.000Z",
    filePath: "/books/Journey to Ixtlan The Lessons o - Carlos Castaneda.pdf",
    externalLink: "https://adminct-my.sharepoint.com/:b:/r/personal/varun_mallapur_chitrapurmath_net_in/Documents/Scanned%20Books/Eng/Journey%20to%20Ixtlan%20The%20Lessons%20o%20-%20Carlos%20Castaneda.pdf?csf=1&web=1&e=flJexu"
  },
  {
    id: 55,
    title: "In The Still Lake of Contemplation",
    author: "Nochur Sri Venkataraman",
    year: 2007,
    language: "english",
    script: "roman",
    category: "Philosophy",
    description: "A collection of spiritual teachings on mindfulness, meditation, and the journey toward inner peace and self-realization.",
    isbn: "9788188325382",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-10-05T18:30:00.000Z",
    filePath: "/books/In The Still Lake Of Contemplat - Nochur Sri Venkataraman.pdf",
    externalLink: "https://adminct-my.sharepoint.com/:b:/r/personal/varun_mallapur_chitrapurmath_net_in/Documents/Scanned%20Books/Eng/In%20The%20Still%20Lake%20Of%20Contemplat%20-%20Nochur%20Sri%20Venkataraman.pdf?csf=1&web=1&e=M712TW"
  },
  {
    id: 56,
    title: "Heart is Thy Name, Oh Lord",
    author: "Sri Ramana Maharshi",
    year: 2004,
    language: "english",
    script: "roman",
    category: "Philosophy",
    description: "A collection of moments and teachings from Sri Ramana Maharshi, focusing on the heart as the spiritual center.",
    isbn: "9788182880115",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-10-05T18:45:00.000Z",
    filePath: "/books/Heart Is Thy Name Oh Lord_Moments Of Silence With Sri Ramana Maharshi_Sri Ramanashram_Tiruvannamalai.pdf",
    externalLink: "https://adminct-my.sharepoint.com/:b:/r/personal/varun_mallapur_chitrapurmath_net_in/Documents/Scanned%20Books/Eng/Heart%20Is%20Thy%20Name%20Oh%20Lord_Moments%20Of%20Silence%20With%20Sri%20Ramana%20Maharshi_Sri%20Ramanashram_Tiruvannamalai..pdf?csf=1&web=1&e=2aiYr1"
  },
  {
    id: 57,
    title: "Hand of Destiny",
    author: "C Subramaniam",
    year: 1993,
    language: "english",
    script: "roman",
    category: "Other",
    description: "The autobiography of C. Subramaniam, chronicling his role in India's political and agricultural development.",
    isbn: "9788172760076",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-10-05T19:00:00.000Z",
    filePath: "/books/Hand Of Destiny Volume One The Turning Poi - C.Subramanian Bharatiya Vidya Bhavan, Bomb.pdf",
    externalLink: "https://adminct-my.sharepoint.com/:b:/r/personal/varun_mallapur_chitrapurmath_net_in/Documents/Scanned%20Books/Eng/Hand%20Of%20Destiny%20Volume%20One%20The%20Turning%20Poi%20-%20C.Subramanian%20Bharatiya%20Vidya%20Bhavan,%20Bomb.pdf?csf=1&web=1&e=bw6zxH"
  },
  {
    id: 58,
    title: "Gokarn Across Bharat",
    author: "Nitin R Gokarn",
    year: 2024,
    language: "english",
    script: "roman",
    category: "Philosophy",
    description: "A philosophical journey across the cultural and spiritual landscape of India through the eyes of the author.",
    isbn: "9780123456781",
    coverImage: "/images/book_icon.jpg",
    dateAdded: "2025-10-05T19:15:00.000Z",
    filePath: "/books/Gokarn Across Bharath_Author Nitin Gokarn.pdf",
    externalLink: "https://adminct-my.sharepoint.com/:b:/r/personal/varun_mallapur_chitrapurmath_net_in/Documents/Scanned%20Books/Eng/Gokarn%20Across%20Bharath_Author%20Nitin%20Gokarn.pdf?csf=1&web=1&e=aWFlu3"
  }
];
